- name: Instalar dependencias
  apt:
    name:
      - php
      - curl
      - php-mysql
      - php-xml
      - php-curl
      - php-mbstring
      - wget
    state: present
    update_cache: yes

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copiar archivos de WordPress al DocumentRoot
  copy:
    src: /tmp/wordpress/
    dest: "{{ wp_document_root }}/"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copiar archivo de configuración de WordPress
  template:
    src: wp-config.php.j2  
    dest: "{{ wp_document_root }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Reiniciar Apache

- name: Configurar VirtualHost
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/wp.{{ wp_vhost_name }}.conf"
  notify: Reiniciar Apache

- name: Configurar permisos
  file:
    path: "{{ wp_document_root }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Activar el VirtualHost
  command: a2ensite "wp.{{ wp_vhost_name }}.conf"
  notify: Reiniciar Apache

- name: Descargar WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

- name: Verificar instalación de WP-CLI
  command: wp --info
  register: wp_info
  failed_when: wp_info.rc != 0

- name: Configurar WordPress
  command: >
    wp core install --url="http://{{ ansible_hostname }}" --title="My WordPress Site"
    --admin_user="{{ wordpress_admin_user }}" --admin_password="{{ wordpress_admin_password }}"
    --admin_email="{{ wordpress_admin_email }}" --path="{{ wp_document_root }}" --allow-root
  args:
    chdir: "{{ wp_document_root }}"

