Vagrant.configure("2") do |config|

    # Máquina Router
    config.vm.define :router do |router|
        router.vm.box = "debian/bookworm64"
        router.vm.hostname = "router"
    
        # Configuración de red pública
        router.vm.network   :public_network,
                            :dev => "br0",
                            :mode => "bridge",
                            :type => "bridge"

        # Configuración de red privada 'red_intra'
        router.vm.network   :private_network,
                            :libvirt__network_name => "red-intra",
                            :libvirt__dhcp_enabled => false,
                            :ip => "192.168.200.100",
                            :libvirt__forward_mode => "veryisolated"

    
        # Deshabilitar la carpeta compartida
        router.vm.synced_folder ".", "/vagrant", disabled: true
    end
    
    # Máquina BD
    config.vm.define :bd do |bd|
        bd.vm.box = "debian/bookworm64"
        bd.vm.hostname = "bd"
      
        # Conectar a 'red_intra'
        bd.vm.network   :private_network,
                        :libvirt__network_name => "red-intra",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.200.101",
                        :libvirt__forward_mode => "veryisolated"
  
        # Conectar a 'red_datos'
        bd.vm.network   :private_network,
                        :libvirt__network_name => "red-datos",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.100.101",
                        :libvirt__forward_mode => "veryisolated"

        bd.vm.synced_folder ".", "/vagrant", disabled: true
    end  
  
    # Máquina Web
    config.vm.define :web do |web|
        web.vm.box = "debian/bookworm64"
        web.vm.hostname = "web"
      
        # Conectar a 'red_intra'
        web.vm.network  :private_network,
                        :libvirt__network_name => "red-intra",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.200.102",
                        :libvirt__forward_mode => "veryisolated"
  
        # Conectar a 'red_datos'
        web.vm.network  :private_network,
                        :libvirt__network_name => "red-datos",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.100.102",
                        :libvirt__forward_mode => "veryisolated"

        web.vm.synced_folder ".", "/vagrant", disabled: true
    
    end

    # Máquina cliente
    config.vm.define :cliente do |cliente|
        cliente.vm.box = "debian/bookworm64"
        cliente.vm.hostname = "cliente"
      
        # Conectar a 'red_intra'
        cliente.vm.network  :private_network,
                        :libvirt__network_name => "red-intra",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.200.104",
                        :libvirt__forward_mode => "veryisolated"

        cliente.vm.synced_folder ".", "/vagrant", disabled: true
    
    end


    # Máquina SAN
    config.vm.define :san do |san|
        san.vm.box = "debian/bookworm64"
        san.vm.hostname = "san"
  
        # Conectar a 'red_intra'
        san.vm.network  :private_network,
                        :libvirt__network_name => "red-intra",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.200.103",
                        :libvirt__forward_mode => "veryisolated"
  
        # Conectar a 'red_datos'
        san.vm.network  :private_network,
                        :libvirt__network_name => "red-datos",
                        :libvirt__dhcp_enabled => false,
                        :ip => "192.168.100.103",
                        :libvirt__forward_mode => "veryisolated"

        san.vm.synced_folder ".", "/vagrant", disabled: true

        # Añadir tres discos de 2G cada uno para el RAID5
        san.vm.provider :libvirt do |libvirt|
            libvirt.storage :file, size: "2G", path: "san_disk1.qcow2"
            libvirt.storage :file, size: "2G", path: "san_disk2.qcow2"
            libvirt.storage :file, size: "2G", path: "san_disk3.qcow2"
        end
    end  
end
  