- name: Actualizamos el sistema
  apt:
    update_cache: yes
    upgrade: yes


# - name: Copiar clave pública en cada nodo
#   authorized_key:
#     user: "{{ usuario }}" 
#     state: present
#     key: "{{ lookup('file', '/home/alex/id_rsa.pub') }}"
