- name: Comprobar la ruta por defecto actual
  command: ip route show default
  register: current_route
  ignore_errors: true

- name: Cambiar la ruta por defecto solo si es necesario
  shell: |
    ip route delete default
    ip route add default via "{{ ip_router }}"
  when: "'default' in current_route.stdout and ip_router not in current_route.stdout"
  become: true

- name: Asegurarse de que la entrada está presente en /etc/network/interfaces
  lineinfile:
    path: /etc/network/interfaces
    line: "post-up route add -net '{{ red_interna_sin_mascara }}' netmask '{{ mascara }}' gw '{{ red_interna_sin_mascara }}' dev '{{ interfaz_router }}'"
    state: present
  become: true
