- name: Asegurarse de que MariaDB esté instalado
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: present

- name: Crear base de datos para WordPress
  mysql_db:
    name: "{{ wordpress_db }}"
    state: present

- name: Crear usuario de base de datos para WordPress
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db }}.*:ALL"
    state: present

- name: Conceder permisos a {{ wordpress_db_user }} en la base de datos {{ wordpress_db }}
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    host: "192.168.200.%"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db }}.*:ALL"
    state: present

- name: Permitir que MariaDB escuche en todas las interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address            = 127.0.0.1"
    line: "bind-address            = 0.0.0.0"
    state: present
  notify:
    - restart mariadb


