- hosts: all
  become: true
  roles:
    - role: commons

- hosts: router
  become: true
  roles:
    - role: router 

#  -hosts: san web bd
#   become: true
#   roles:
#     - role: redinterna

# - hosts: san
#   become: true
#   roles:
#     - role: sab

# - hosts: bd
#   become: true
#   roles:
#     - role: mariadb

#  - hosts: web
#   become: true
#   roles:
#       role: web


