- name: Cambia el bit de forward a 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Configuración de DNAT
  iptables:
    chain: PREROUTING
    in_interface: "{{ interfaz_router }}"  # Interfaz pública en el router
    destination_port: 80
    jump: DNAT
    protocol: tcp
    table: nat
    to_destination: "{{ ip_servidor_web }}:80"  # IP y puerto de la máquina web

- name: Configurar SNAT para permitir salida a Internet desde red_intra
  iptables:
    chain: POSTROUTING
    source: "{{ red_interna }}"             # Rango de IP de la red interna red_intra
    jump: MASQUERADE
    out_interface: "{{ interfaz_router }}"      # Interfaz conectada a Internet
    table: nat

- name: "iptables persistent"
  apt:
    pkg:
      - iptables-persistent

- name: Guardar el estado actual del firewall en el archivo del sistema
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
  notify: Reiniciar iptables

